"""
SQLAS Schema Retrieval Quality — measures how well the schema index serves each query.

The existing schema_compliance metric answers: "Do the tables/columns used in
the SQL exist in the database?" (validates output).

This module answers the UPSTREAM question: "Did the schema retrieval step return
the RIGHT tables for this query?" (validates the retrieval step itself).

Three metrics:
  retrieval_precision  — of tables retrieved, what fraction were actually needed?
  retrieval_recall     — of tables actually needed, what fraction were retrieved?
  retrieval_f1         — harmonic mean of precision and recall

"Needed" is determined by either:
  a) The tables actually referenced in the generated SQL (auto-detected via sqlglot)
  b) The expected_tables from the TestCase (gold standard)

Usage:
    from sqlas import schema_retrieval_quality

    # What the schema index returned
    retrieved = {"patients", "physical_activity", "lab_results", "medications"}

    # What the generated SQL actually used (auto-detected if not provided)
    generated_sql = "SELECT p.age, AVG(pa.steps) FROM patients p JOIN physical_activity pa..."

    score, details = schema_retrieval_quality(
        retrieved_tables = retrieved,
        generated_sql    = generated_sql,
        gold_tables      = {"patients", "physical_activity"},  # from TestCase
    )
    print(score)                    # 0.83
    print(details["precision"])     # 0.50  (2 of 4 retrieved were needed)
    print(details["recall"])        # 1.00  (both needed tables were retrieved)
    print(details["irrelevant"])    # ["lab_results", "medications"]
    print(details["missing"])       # []

Integration with run_suite():
    Pass retrieved_tables_fn — a callable that returns the tables the schema index
    retrieved for a given question:

        def get_retrieved(question):
            return schema_index.retrieve_relevant_tables(question)

        results = run_suite(
            ...,
            retrieved_tables_fn = get_retrieved,
        )
        print(results["summary"]["avg_retrieval_f1"])
"""

import re
from typing import Optional

try:
    import sqlglot
    from sqlglot import exp as sqlexp
    _HAS_SQLGLOT = True
except ImportError:
    _HAS_SQLGLOT = False


def _extract_used_tables(sql: str) -> set[str]:
    """Extract table names actually referenced in generated SQL using sqlglot AST."""
    if not _HAS_SQLGLOT:
        # Fallback: regex-based extraction
        pattern = r'\bFROM\s+([`"\[]?[\w]+[`"\]]?)|\bJOIN\s+([`"\[]?[\w]+[`"\]]?)'
        tables = set()
        for m in re.finditer(pattern, sql, re.IGNORECASE):
            t = (m.group(1) or m.group(2) or "").strip('`"[]').lower()
            if t and t not in ("select", "where", "on", "and", "or"):
                tables.add(t)
        return tables
    try:
        parsed = sqlglot.parse_one(sql)
        return {t.name.lower() for t in parsed.find_all(sqlexp.Table) if t.name}
    except Exception:
        return set()


def schema_retrieval_quality(
    retrieved_tables: set[str],
    generated_sql: str,
    gold_tables: Optional[set[str]] = None,
    used_tables: Optional[set[str]] = None,
) -> tuple[float, dict]:
    """
    Measure schema retrieval quality: did the index return the right tables?

    Precision and recall are computed against "relevant" tables, which is:
      1. gold_tables if provided (most accurate — from TestCase.expected_tables)
      2. used_tables if provided (what the SQL actually referenced)
      3. Tables extracted from generated_sql via sqlglot AST (auto-detected)

    Args:
        retrieved_tables: Set of table names returned by the schema index.
        generated_sql:    The SQL generated by the agent (for auto table extraction).
        gold_tables:      Expected tables from TestCase (most reliable ground truth).
        used_tables:      Override for auto-extracted tables from SQL.

    Returns:
        (f1_score, details_dict) where details includes precision, recall,
        irrelevant tables (retrieved but not needed), and missing tables
        (needed but not retrieved).
    """
    ret_lower  = {t.lower() for t in retrieved_tables}

    # Determine the "relevant" set
    if gold_tables is not None:
        relevant = {t.lower() for t in gold_tables}
        relevance_source = "gold_tables"
    elif used_tables is not None:
        relevant = {t.lower() for t in used_tables}
        relevance_source = "used_tables"
    else:
        relevant = _extract_used_tables(generated_sql)
        relevance_source = "auto_extracted_from_sql"

    if not relevant:
        return 1.0, {
            "note": "no relevant tables to evaluate against",
            "retrieved": sorted(ret_lower),
            "relevance_source": relevance_source,
        }

    if not ret_lower:
        return 0.0, {
            "precision": 0.0, "recall": 0.0, "f1": 0.0,
            "retrieved": [], "relevant": sorted(relevant),
            "missing": sorted(relevant),
            "irrelevant": [],
            "relevance_source": relevance_source,
            "note": "no tables were retrieved",
        }

    tp = ret_lower & relevant          # retrieved AND needed
    irrelevant = ret_lower - relevant  # retrieved but NOT needed (noise)
    missing    = relevant - ret_lower  # needed but NOT retrieved (gaps)

    precision = len(tp) / len(ret_lower) if ret_lower else 0.0
    recall    = len(tp) / len(relevant)  if relevant  else 0.0
    f1        = (2 * precision * recall / (precision + recall)
                 if (precision + recall) > 0 else 0.0)

    # FK expansion quality: were all JOIN-required tables included?
    fk_penalty = 0.0
    if missing:
        # Penalise missing tables more if they appear in JOIN clauses
        sql_upper = generated_sql.upper()
        join_tables = set()
        for m in re.finditer(r'\bJOIN\s+([`"\[]?[\w]+[`"\]]?)', sql_upper):
            join_tables.add(m.group(1).strip('`"[]').lower())
        missing_joins = missing & join_tables
        if missing_joins:
            fk_penalty = 0.1 * len(missing_joins)

    score = max(0.0, round(f1 - fk_penalty, 4))

    return score, {
        "score":             score,
        "precision":         round(precision, 4),
        "recall":            round(recall, 4),
        "f1":                round(f1, 4),
        "fk_penalty":        round(fk_penalty, 4),
        "retrieved":         sorted(ret_lower),
        "relevant":          sorted(relevant),
        "true_positives":    sorted(tp),
        "irrelevant":        sorted(irrelevant),
        "missing":           sorted(missing),
        "relevance_source":  relevance_source,
        "coverage_rate":     f"{len(tp)}/{len(relevant)} needed tables retrieved",
        "noise_rate":        f"{len(irrelevant)}/{len(ret_lower)} retrieved tables were unnecessary",
    }


def batch_retrieval_quality(
    evaluations: list[dict],
) -> dict:
    """
    Aggregate schema retrieval quality across multiple evaluations.

    Each dict in evaluations should have:
        retrieved_tables, generated_sql, and optionally gold_tables.

    Returns:
        Summary with avg_f1, avg_precision, avg_recall, worst_cases.
    """
    results = []
    for ev in evaluations:
        score, details = schema_retrieval_quality(
            retrieved_tables = ev.get("retrieved_tables", set()),
            generated_sql    = ev.get("generated_sql", ""),
            gold_tables      = ev.get("gold_tables"),
        )
        results.append({**details, "question": ev.get("question", "")})

    if not results:
        return {"n": 0}

    n = len(results)
    avg_f1        = sum(r["f1"] for r in results) / n
    avg_precision = sum(r["precision"] for r in results) / n
    avg_recall    = sum(r["recall"] for r in results) / n

    worst = sorted(results, key=lambda r: r["f1"])[:3]

    return {
        "n":             n,
        "avg_f1":        round(avg_f1, 4),
        "avg_precision": round(avg_precision, 4),
        "avg_recall":    round(avg_recall, 4),
        "worst_cases":   [{"question": w["question"], "f1": w["f1"],
                           "missing": w["missing"]} for w in worst],
    }
